### PR TITLE
Mono Repo Support

### PR DESCRIPTION
**Pull request by keithburgoyne**
To test:

**Test with a non-monorepo.**
1. Check this PR out.
1. Go into `/so/sites/emrap/live`
1. Run `/so/packages/package_release/work-yourname/bin/prepare-site`
1. Ensure that everything looks correct.
1. Follow the on-screen instructions to check out live and delete the branch.

**Test with a monorepo**
1. Check this PR out.
1. Go into `/so/sites/emrap-corependium/live/client`
1. Run `/so/packages/package_release/work-yourname/bin/prepare-site`
1. Ensure that everything looks correct.
1. Follow the on-screen instructions to check out live and delete the branch.
1. Go into `/so/sites/emrap-corependium/live/server`
1. Run `/so/packages/package_release/work-yourname/bin/prepare-site`
1. Ensure that everything looks correct.
1. Follow the on-screen instructions to check out live and delete the branch.

### CODE REVIEW

**Comment by keithburgoyne** [comment]
Sites without a `release-metadata.ini` file should assume the site is a non-monorepo, and should use the defaults.

**Comment by jaymefSO** [comment]
> Sites without a `release-metadata.ini` file should assume the site is a non-monorepo, and should use the defaults.

also:

what happens when a new component is added to a mono repo?  The details for it will not exist in the release-metadata.ini file in the live directory where prepare-site is being run from.

**Comment by keithburgoyne** [comment]
>what happens when a new component is added to a mono repo? The details for it will not exist in the release-metadata.ini file in the live directory where prepare-site is being run from.

I'm of two minds: we either work out a hacky solution to either merge in the ini into the live branch as a first step, or we make it a manual process when setting up a new module.

**Comment by jaymefSO** [comment]
I've tested this myself along with Keith.  The tool has been used to sync the emrap-coreP monorepo project several times successfully.  It has also been used to sync a non-mono repo site Neon successfully.   It's an R+ from me, but a quick review of the PHP code by a dev would be helpful before merging.

**Comment by fokked** [comment]
https://app.clubhouse.io/silverorangeinc/story/7326/monorepo-stuff

**Comment by keithburgoyne** [comment]
[ch7326]

**Pull request merged**
